app_forgot_password_request:
  path: /reset-password
  controller: App\Controller\ResetPasswordController::request

app_login:
  path: /connexion
  controller: App\Controller\SecurityController::login
  
app_register:
  path: /inscription
  controller: App\Controller\RegistrationController::register

app_verify_email:
  path: /verify/email
  controller: App\Controller\RegistrationController::verifyUserEmail

contact:
  path: /contact
  controller: App\Controller\ContactController::index

home_index:
  path: /
  controller: App\Controller\HomeController::index

message:
  path: /chat
  controller: App\Controller\MessagesController::index

message_recover:
  path: /chat/recover{lastid}
  controller: App\Controller\MessagesController::recover

message_add:
  path: /chat/add
  controller: App\Controller\MessagesController::add

play_lobby:
  path: /jouer
  controller: App\Controller\PlayController::lobby

play_join:
  path: /jouer/rejoindre
  controller: App\Controller\PlayController::join

play_play:
  path: /jouer/partie{id}
  controller: App\Controller\PlayController::play

scenario_create:
  path: /scenario/creation
  controller: App\Controller\ScenarioController::create

scenario_delete:
  path: /scenario/delete{id}
  controller: App\Controller\ScenarioController::delete

scenario_deleteFrame:
  path: /scenario/update/deleteFrame{id}
  controller: App\Controller\ScenarioController::deleteFrame

scenario_frameCreate:
  path: /scenario/update/frameCreate{id}
  controller: App\Controller\ScenarioController::frameCreate

scenario_frameUpdate:
  path: /scenario/update/frameUpdate{id}
  controller: App\Controller\ScenarioController::frameUpdate

scenario_index:
  path: /scenario
  controller: App\Controller\ScenarioController::index

scenario_update:
  path: /scenario/update{id}
  controller: App\Controller\ScenarioController::update

scenario_view:
  path: /scenario/view{id}
  controller: App\Controller\ScenarioController::view