
home_index:
  path: /
  controller: App\Controller\HomeController::index

play_index:
  path: /jouer
  controller: App\Controller\PlayController::index

play_play:
  path: /jouer/scenario={id}
  controller: App\Controller\PlayController::play
  
scenario_index:
  path: /scenario
  controller: App\Controller\ScenarioController::index

scenario_create:
  path: /scenario/creation
  controller: App\Controller\ScenarioController::create

scenario_update:
  path: /scenario/update{id}
  controller: App\Controller\ScenarioController::update

scenario_frameCreate:
  path: /scenario/update/frameCreate
  controller: App\Controller\ScenarioController::frameCreate

scenario_frameUpdate:
  path: /scenario/update/frameUpdate{id}
  controller: App\Controller\ScenarioController::frameUpdate

scenario_deleteFrame:
  path: /scenario/update/deleteFrame{id}
  controller: App\Controller\ScenarioController::deleteFrame

scenario_delete:
  path: /scenario/delete{id}
  controller: App\Controller\ScenarioController::delete

app_register:
  path: /register
  controller: App\Controller\RegistrationController::register

app_verify_email:
  path: /verify/email
  controller: App\Controller\RegistrationController::verifyUserEmail

app_forgot_password_request:
  path: /reset-password
  controller: App\Controller\ResetPasswordController::request

